############################################################################
######################         ribbon-zuul           #######################
############################################################################
spring:
  application:
    name: ribbon-zuul

server:
  port: 8401
#  port: ${PORT:${SERVER_PORT:0}}
    
eureka:
  client:
    serviceUrl:      
      defaultZone: http://lishangzhi:123456@localhost:8101/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}   
 
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: CLIENTRIBBON
    api-b:
      path: /api-b/**
      serviceId: CLIENTFEIGN
 
      

