############################################################################
######################         server-zipkin         #######################
############################################################################
spring:
  application:
    name: server-zipkin

server:
  port: 8501
#  port: ${PORT:${SERVER_PORT:0}}
 
      

